### ISSUE TITLE
Any suggestion about supporting old libraries?

### ISSUE THREAD

**Issue by plopesc** [bojanz/ludwig#11]
Trying to integrate Geofield module with Ludwig, the ludwig.json file works great.

However, [geoPHP](https://github.com/phayes/geoPHP) library is quite outdated, and it does not support psr-0 or psr-4. It works using composer, but not sure whether you could support this in Ludwig.

Could you provide any feedback?

**Comment by bojanz** [comment]
No clue what we can do in that case. Ludwig was built for PSR0/PSR4, it works by extending the list of core namespaces.

It would probably be easier for you to find a modern library fork, than invent a way for Ludwig to include the independent files.

**Comment by plopesc** [comment]
That's what I thought... Thank you for your interest and quick response!
