### ISSUE TITLE
Investigate alternatives to update manager functions in PackageDownloader

### ISSUE THREAD

**Issue by bojanz** [bojanz/ludwig#3]
Right now PackageDownloader depends on the update module to do its thing.
Ideally we'd have a way to do this that doesn't require a bootstrapped Drupal instance.
Worth looking at what Console / Drush are doing, seeing if there are any tricks we can steal.

**Comment by mglaman** [comment]
Well, wouldn't we need a bootstrapped instance so we know what modules are valid? I assumed the package manager looked up all installed modules.

It'd be fairly simple to use the Symfony FileSystem or plain PHP to move the files. I just figured best to copy how core runs it. Albeit I wanted to port the code into our own service, removing dependency.

Both Drush and Console have a means to discover module locations. We could use that and just install everyone found. But that'd also prevent us from using PackageManager for details.

**Comment by bojanz** [comment]
> Well, wouldn't we need a bootstrapped instance so we know what modules are valid? I assumed the package manager looked up all installed modules.

I just committed a fix for that (a port of the composer_manager logic). See #4

**Comment by bojanz** [comment]
This got resolved in #6.
